# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs.

[tox]
envlist = py38,py39,py310,py311,py312

[testenv]
deps =
    pytest
    pytest-cov

commands =
    pytest \
        --verbose \
        --cov=wparc \
        --cov-report=term-missing \
        tests/
